version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    restart: always
    volumes:
      - .:/opt/app/api
    environment:
      APP_PORT: 4321
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: db_demo_dev
    ports:
      - 4321:4321
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_demo_dev
    ports:
      - 3333:3306
volumes:
  dbdata: