apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ddd-ingress
  namespace: demo-ddd
  labels:
    name: demo-ddd-ingress
spec:
  rules:
  - host: anang.su13
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demo-ddd-service-local
            port: 
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-ddd-service-local
  namespace: demo-ddd
spec:
  selector:
    app: demo-ddd-app-local
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ddd-app-local
  namespace: demo-ddd
spec:
  selector:
    matchLabels:
      app: demo-ddd-app-local
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-ddd-app-local
    spec:
      containers:
      - name: demo-ddd-app-local
        image: anangsu13/ddd-demo-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        env:
        - name: APP_NAME
          value: "demo-ddd-app-local"
        - name: APP_PORT
          value: "5000"
        startupProbe:
          httpGet:
            path: /v1/demo/info
            port: 5000
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10